### ISSUE TITLE
Traceback: TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by sambatlim** [Polymorphe57/hello_world_view_code#1]
When I run your addon on Odoo version 13, It give me this error:

```
Traceback:
TypeError: Cannot read property 'prototype' of undefined
    at Class.getController (http://localhost:8069/web/content/628-30868b9/web.assets_backend.js:1071:777)
    at Class.prototype.<computed> [as getController] (http://localhost:8069/web/content/330-00aa9f2/web.assets_common.js:3861:488)
    at http://localhost:8069/web/content/628-30868b9/web.assets_backend.js:441:780
    at new Promise (<anonymous>)
    at Class._createViewController (http://localhost:8069/web/content/628-30868b9/web.assets_backend.js:441:721)
    at http://localhost:8069/web/content/628-30868b9/web.assets_backend.js:446:169
```

**Comment by sambatlim** [comment]
error fixed: #2
